<?php

$labels = [];
$labels['task_title'] = 'Delivery Logs';
$labels['search_message_id'] = 'By Message-ID';
$labels['search_sender_recipient'] = 'By sender/recipient';
$labels['message_id'] = 'Message-ID';
$labels['sender_recipient'] = 'Sender/Recipient';
$labels['date_from'] = 'From';
$labels['date_to'] = 'To';
$labels['search'] = 'Search';
$labels['no_results'] = 'No log entries found.';
$labels['download'] = 'Download as TXT';
$labels['es_connect_error'] = 'Could not connect to the log server. Please try again later.';
$labels['es_query_error'] = 'An error occurred while searching logs. Please try again later.';
$labels['elasticlogs_settings_title'] = 'Delivery Logs';
$labels['messagesearch'] = 'Trace message';
$labels['search_all'] = 'Search all logs';
