<?php

$labels = [];
$labels['task_title'] = 'Registos de Entrega';
$labels['search_message_id'] = 'Por Message-ID';
$labels['search_sender_recipient'] = 'Por remetente/destinatário';
$labels['message_id'] = 'Message-ID';
$labels['sender_recipient'] = 'Remetente/Destinatário';
$labels['date_from'] = 'De';
$labels['date_to'] = 'Até';
$labels['search'] = 'Pesquisar';
$labels['no_results'] = 'Nenhum registo encontrado.';
$labels['download'] = 'Descarregar como TXT';
$labels['es_connect_error'] = 'Não foi possível ligar ao servidor de registos. Tente novamente mais tarde.';
$labels['es_query_error'] = 'Ocorreu um erro ao pesquisar registos. Tente novamente mais tarde.';
$labels['elasticlogs_settings_title'] = 'Registos de Entrega';
$labels['messagesearch'] = 'Rastrear mensagem';