all: compile watch

compile:
	sass src/styles.scss:styles.css src/embed.scss:embed.css src/print.scss:print.css

watch:
	sass --watch src/styles.scss:styles.css src/embed.scss:embed.css src/print.scss:print.css
