<?php

$labels['registered_checkbox'] = 'Registered mail';
$labels['settings_label'] = 'Registered email';
$labels['settings_title'] = 'Registered email settings';
$labels['register_all_emails'] = 'Register all emails';
$labels['yes'] = 'Yes';
$labels['no_default_active'] = 'No. Only emails marked as registered via webmail';
$labels['save'] = 'Save';
$labels['available_timestamps'] = 'Available timestamps this month';
$labels['pagetitle.upgrade'] = 'Upgrade';
$labels['settings_settings_section_title'] = 'Settings';
$labels['settings_subscription_section_title'] = 'Subscription';
$labels['subscription_pending_payment'] = 'You have a subscription pending payment. Please complete the payment to activate the subscription.';