<?php

$labels['registered_checkbox'] = 'Email registado';
$labels['settings_label'] = 'Email registado';
$labels['settings_title'] = 'Configurações de email registado';
$labels['register_all_emails'] = 'Registar todos os emails enviados';
$labels['yes'] = 'Sim';
$labels['no_default_active'] = 'Não. Apenas os emails marcados como registados via webmail';
$labels['save'] = 'Guardar';
$labels['available_timestamps'] = 'Selos de registo disponíveis este mês';
$labels['pagetitle.upgrade'] = 'Upgrade';
$labels['settings_settings_section_title'] = 'Configurações';
$labels['settings_subscription_section_title'] = 'Assinatura';
$labels['subscription_pending_payment'] = 'Tem uma assinatura pendente de pagamento. Por favor complete o pagamento para activar a assinatura.';