<?php

$labels['forgot_password']  = 'Forgot password';
$labels['email'] = 'Email';
$labels['email_placeholder'] = 'john.doe@example.com';
$labels['recover_password'] = 'Recover password';
$labels['confirm_recovery_email'] = 'Confirm recovery email';
$labels['confirm_recovery_phone'] = 'Confirm recovery phone';
$labels['recovery_code'] = 'Recovery code';
$labels['password'] = 'Password';
$labels['password_confirm'] = 'Confirm password';
$labels['change_password'] = 'Change password';
$labels['recovery_code_instructions'] = 'Please enter the recovery code you received by email or SMS.';
$labels['password_restriction_confirmation'] = 'Passwords and confirmation must match';
$labels['password_restriction_length'] = 'Password must be at least 8 characters long';
$labels['password_restriction_case'] = 'Password must contain at least one uppercase and one lowercase letter';
$labels['password_restriction_digit'] = 'Password must contain at least one digit';
$labels['password_restriction_nonalpha'] = 'Password must contain at least one non-alphanumeric character';
$labels['password_changed'] = 'Password changed successfully';
$labels['return_to_login'] = 'Return to login';