<?php

$labels['forgot_password']  = 'Recuperar password';
$labels['email'] = 'Email';
$labels['email_placeholder'] = 'john.doe@example.com';
$labels['recover_password'] = 'Recuperar password';
$labels['confirm_recovery_email'] = 'Confirme email de recuperação';
$labels['confirm_recovery_phone'] = 'Confirme telemóvel de recuperação';
$labels['recovery_code'] = 'Código de recuperação';
$labels['password'] = 'Password';
$labels['password_confirm'] = 'Confirme a password';
$labels['change_password'] = 'Mudar password';
$labels['recovery_code_instructions'] = 'Por favor introduza o código de recuperação que recebeu por email ou SMS';
$labels['password_restriction_confirmation'] = 'A password e a confirmação devem coincidir';
$labels['password_restriction_length'] = 'A password deve ter pelo menos 8 caracteres';
$labels['password_restriction_case'] = 'A password deve conter pelo menos uma letra maiúscula e uma letra minúscula';
$labels['password_restriction_digit'] = 'A password deve conter pelo menos um dígito';
$labels['password_restriction_nonalpha'] = 'A password deve conter pelo menos um caracter não alfanumérico';
$labels['password_changed'] = 'Password alterada com sucesso';
$labels['return_to_login'] = 'Voltar à página de login';


